### ISSUE TITLE
Reflections Fehler beim Startup

### ISSUE THREAD

**Issue by valentinlehmann** [valentinlehmann/contentutils#7]
Folgender Fehler tritt beim Start auf, eventueller Zusammenhang mit Java 15.

```
[11:06:01] [Server thread/ERROR]: Error occurred while enabling ContentUtils v1.2.0-SNAPSHOT (Is it up to date?)
org.reflections.ReflectionsException: Scanner SubTypesScanner was not configured
    at org.reflections.Store.get(Store.java:39) ~[?:?]
    at org.reflections.Store.get(Store.java:61) ~[?:?]
    at org.reflections.Store.get(Store.java:46) ~[?:?]
    at org.reflections.Store.getAll(Store.java:93) ~[?:?]
    at org.reflections.Reflections.getSubTypesOf(Reflections.java:404) ~[?:?]
    at de.valentinlehmann.contentutils.utils.ClassPathUtils.getAllClassesInPackage(ClassPathUtils.java:17) ~[?:?]
    at de.valentinlehmann.contentutils.utils.ClassPathUtils.createInstanceAndApplyAction(ClassPathUtils.java:27) ~[?:?]
    at de.valentinlehmann.contentutils.ContentUtilsPlugin.onEnable(ContentUtilsPlugin.java:43) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:1.9.3-SNAPSHOT]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:333) [spigot.jar:1.9.3-SNAPSHOT]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:408) [spigot.jar:1.9.3-SNAPSHOT]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:307) [spigot.jar:1.9.3-SNAPSHOT]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:267) [spigot.jar:1.9.3-SNAPSHOT]
    at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:349) [spigot.jar:1.9.3-SNAPSHOT]
    at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:313) [spigot.jar:1.9.3-SNAPSHOT]
    at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:279) [spigot.jar:1.9.3-SNAPSHOT]
    at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:195) [spigot.jar:1.9.3-SNAPSHOT]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:483) [spigot.jar:1.9.3-SNAPSHOT]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_302]
```

**Comment by valentinlehmann** [comment]
Steht nicht im Zusammenhang mit Java 15, hatte hier falsche Informationen. Dennoch scheint mir ein Zusammenhang mit verschiedenen JDKs zu bestehen, da es auf meinem Testserver einwandfrei funktioniert hat.

Version meines Servers: Java(TM) SE Runtime Environment (build 1.8.0_281-b09)
Version des Servers mit Fehlern: OpenJDK Runtime Environment Corretto-8.302.08.1

**Comment by valentinlehmann** [comment]
Fehler wurde durch einen Wechsel der Reflections API behoben. Anders als der Name der neuen Dependency (`net.oneandone.reflections8:reflections8`) vermuten lässt, ist das Plugin trotzdem Java 15/16 kompatibel (zumindest auf meinem Testserver).
